### ISSUE TITLE
Add option to disable slimv indent plugins

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/slimv#105]
Is there a way to disable the indent plugins provided by slimv (i.e. `slimv/indent/lisp.vim`, `slimv/indent/scheme.vim`, `slimv/indent/clojure.vim`)? I would like to keep the default vim indentation behavior provided by its bundled filetype plugins. If no such option exists, would it be possible to add an option to disable the indentation provided by slimv?

**Comment by kovisoft** [comment]
Added option `g:slimv_indent_disable`. If you set it to 1 in your `.vimrc` then slimv won't override vim's built-in indenting. See commit https://github.com/kovisoft/slimv/commit/f8c2f99cd87b024d035e29815f7af32b414124e9
