### ISSUE TITLE
Slimv not working with sbcl 2.1.0

### ISSUE THREAD

**Issue by Kingsy** [kovisoft/slimv#106]
Hi,

So when starting the swank server I get the following error

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "%CODE-ENTRY-POINTS" not found in the SB-KERNEL package.
;   
;       Line: 1613, Column: 48, File-Position: 65201
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/chris/.config/nvim/plugged/slimv/slime/swank/sbcl.lisp" {1003CE1703}>
;; 
;; Error compiling /home/chris/.config/nvim/plugged/slimv/slime/swank/sbcl.lisp:
;;   COMPILE-FILE returned NIL.
;; 
While evaluating the form starting at line 16, column 0
  of #P"/home/chris/.config/nvim/plugged/slimv/slime/start-swank.lisp":

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1004AC8183}>:
  COMPILE-FILE returned NIL.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
```

Is it possilble that the sbcl 2.1.0 release removed some symbols slimv still expects?

My run command for swank in my init.vim neovim config is

```
let g:slimv_swank_cmd = '! xterm -e sbcl --load /home/chris/.config/nvim/plugged/slimv/slime/start-swank.lisp &'
```

Any ideas how we could correct this?

**Comment by Kingsy** [comment]
Yes, downgrading to 2.0.9 fixes the problem. :(

So I guess slimv is broken on the new sbcl version

**Comment by kovisoft** [comment]
Thank you for reporting this problem. It seems that you are absolutely right: sbcl 2.1.0 release removed some symbols slimv still expects. In fact the broken code is borrowed from SLIME, so I need to upgrade the SLIME sources in slimv. I'll come back to you when it's ready.

**Comment by kovisoft** [comment]
Upgraded to SLIME 2.26, this version should be compatible with sbcl 2.1.0. See commit https://github.com/kovisoft/slimv/commit/5064aa35f913dac2a970c35dae4437044f95b87c

**Comment by Kingsy** [comment]
Just upgraded again and all is working perfect.

Thanks for the quick reply and update. amazing!
Love the plugin! thanks so much for bringing lisp to vim!
