### ISSUE TITLE
mit-scheme doesn't work anymore

### ISSUE THREAD

**Issue by ztasre** [kovisoft/slimv#107]
Out of the box, mit-scheme doesn't work.

With and without `g:scheme_builtin_swank = 1` using `,d` causes a bunch of errors but the expression evaluates at the end. Completely unusable regardless.

mit-scheme release is 10.1.11

**Comment by kovisoft** [comment]
Oops! There was a typo in the scheme indent plugin. Thank you for reporting it. Fixed in commit https://github.com/kovisoft/slimv/commit/eab990138729817483788e612f088ac958ef4023

**Comment by ztasre** [comment]
That fixed it! Thank you so much!
