### ISSUE TITLE
Don't display escape characters in REPL

### ISSUE THREAD

**Issue by adampaulukanis** [kovisoft/slimv#116]
Hi.

Thanks for your program!

My problem looks like this:

When I run some tests I see escape characters in the REPL window. I think it should not be displayed.

Any way to disable it, please?

![Screen Shot 2021-08-18 at 11 56 59](https://user-images.githubusercontent.com/1613395/129878948-e22edbf4-6198-4f11-86c8-fbff3350172a.png)

Run in SBCL: 

![Screen Shot 2021-08-18 at 11 57 29](https://user-images.githubusercontent.com/1613395/129878961-5f3b61f1-1bd4-4ed3-b9a7-d96de95565a1.png)

Thank you.

**Comment by kovisoft** [comment]
Thank you for the feedback! Slimv currently does not handle the ansi escape sequences, and unfortunately there is no built-in support in vim for correctly displaying them. I think all I can do is add an option to remove the escape sequences from the output string.

**Comment by kovisoft** [comment]
Added option `g:slimv_strip_ansi` that removes ANSI escape sequences from the REPL output, see commit https://github.com/kovisoft/slimv/commit/df703f197a0eff737c4dd92149c26226218934e9 .

**Comment by adampaulukanis** [comment]
Thanks for this! You are great.

Is there a way to see this option available when I do something like this in Vim:

`:let g:slimv_s<TAB>`

for the first time?

As you can see below, if I don't set this option, I don't see it as available for me.
![Screen Shot 2021-08-23 at 18 37 30](https://user-images.githubusercontent.com/1613395/130484575-39986a79-d716-4490-852f-0ef26ec24175.png)

I guess it should be set to 0 as default option somewhere, perhaps in 'ftplugin/swank.py'?

Thank you for your time.

**Comment by kovisoft** [comment]
I added default value to `g:slimv_strip_ansi`, so it is now displayed in vim's <TAB> completion. See commit https://github.com/kovisoft/slimv/commit/1c1ef6dad577e8c5fb7d94ec3b6d698b68e7730d .

**Comment by adampaulukanis** [comment]
Thanks!
