### ISSUE TITLE
Question on ( and ) in normal mode

### ISSUE THREAD

**Issue by kacoroski** [kovisoft/slimv#137]
Hi,

These keys allow up to move to the enclosing s-exp with the cursor ending on the start of it '(' or the end of it ')'.  I am trying to understand why this is useful as it would seem better to move to the next or previous s-exp by just moving to the next ( or ).  Perhaps there is a different way to move between s-exp that I have not figured out yet.

Thanks,

ski

**Comment by kovisoft** [comment]
Well, this feature was added as a contribution by bitbucket user "dgrnbrg" (he called it 'smartjump') back in the times when slimv/paredit repository was still located on bitbucket.org (and that is gone now). TBH, I don't recall the original motivations. If you have any suggestions for improving this functionality, then let's discuss it.

Currently there are mappings `]]` and `[[` for jumping to the next/previous top level s-expression, maybe that's what you are looking for.

**Comment by kacoroski** [comment]
Ok, I found that I can load vim-sexp after slimv and I get all kinds of s-exp mappings :)  The ones I was looking for are M-], M-[, M-{, and M-}.  As far as I can tell, slimv and vim-sexp work well together.  Closing this out.  Thanks again for creating slimv.
