### ISSUE TITLE
Strange behavior with which-key.nvim

### ISSUE THREAD

**Issue by remexre** [kovisoft/slimv#139]
slimv seems to conflict with which-key.nvim in a very strange way. At first, I thought it simply wasn't working, but the latest time I've tried to reproduce it, running `call SlimvEvalDefun()` (whether from the keybind or from `:`), it sent a defun from an unrelated piece of code in a different project, but still in the package of the file that was currently open. It also put a newline after the current defun.

**Comment by kovisoft** [comment]
Please add this to your `.vimrc`:
```
let g:swank_log = 1
```
This will enable logging the communication between slimv and the swank server. Then please try to reproduce the issue. There will be a swank.log file created in the current directory. Please send me that file (you can find my email in the documentation). Or just paste here the relevant part around the area where the unrelated piece of code is sent to the swank server.
Thanks for the assistance.
