### ISSUE TITLE
incompatible with UltiSnips plugin

### ISSUE THREAD

**Issue by axionix** [kovisoft/slimv#23]
slimv prevents UltiSnips from inserting snippets for some reason, unless g:slimv_disable_* is set to 1.

**Comment by kovisoft** [comment]
How UltiSnips inserts snippets? Or maybe a more proper way of asking it is: what is your UltiSnips configuration for inserting snippets? Is it mapped for the <Tab> key? Is the double mapping of the <Tab> key causing the trouble?

**Comment by axionix** [comment]
A snippet is inserted when pressing enter in insert mode if the preceding text represents a snippet name. I'm unsure if slimv binds <CR> or not.

**Comment by kovisoft** [comment]
Thanks. Yes, slimv maps CR (and Space) for electric return and displaying the function argument list. Now the question is that how this collision should be resolved? Maybe I can add an option in slimv to disable the mapping for CR. But this would of course also disable electric return and arglist-on-enter.

**Comment by axionix** [comment]
Any flag would be appreciated, thanks. I currently do not enable electric return, and I am not worried about either side effects.

**Comment by kovisoft** [comment]
I added the following options: `g:slimv_unmap_cr`, `g:slimv_unmap_tab`, `g:slimv_unmap_space`.
These options may be used to disable the insert mode mappings for the CR, Tab, or Space keys in the editor buffers in Slimv.

**Comment by axionix** [comment]
Thanks!
