### ISSUE TITLE
eval-region doesn't work with clipboard modes

### ISSUE THREAD

**Issue by axionix** [kovisoft/slimv#25]
If "set clipboard" is set to anything other than the default empty value, then eval-region tries to send the wrong code.

**Comment by kovisoft** [comment]
I think your fix solves the `set clipboard=something` case but breaks the `set clipboard=` case.
Shouldn't it be rather something like this, which addresses both cases:
```
    if v:register == '"' || v:register == '+'
        let lines = SlimvGetRegion(a:firstline, a:lastline)
    else
    ...
```

**Comment by axionix** [comment]
Ah, I haven't tried that but I assume it does break it. To be honest, I'm not familiar with VIM that much, so I'll leave you to commit the appropriate change. Thanks :)

**Comment by kovisoft** [comment]
OK, please see commit [c3ebbd055196b505...](https://github.com/kovisoft/slimv/commit/c3ebbd055196b505bea90ecbcc35be5d6cff4e47)
