### ISSUE TITLE
C-w on REPL in insert mode shouldn't remove prompt

### ISSUE THREAD

**Issue by elvis-sik** [kovisoft/slimv#29]
Hi. I am very grateful for this plugin's existence.

I can navigate to the prompt in normal mode and delete it with cw, x, etc. This is not a big deal to me.

But I find it unconvenient that I can remove the prompt with C-w in insert mode. I am used to use C-w to remove what I just typed, and every now and then I will erase the prompt by accident. If there is a way to correct this behaviour, I think it should be done.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/slimv/commit/e76d6e55d2fa2c05a97efb584bd0f455eef8cfe7 .
