### ISSUE TITLE
SlimvAddReplMenu does not respect g:slimv_keybindings and/or cannot be customized

### ISSUE THREAD

**Issue by bvnierop** [kovisoft/slimv#38]
The function `SlimvAddReplMenu` maps `<leader>\` to `:emenu REPL.' . nr2char( &wildcharm )`.

Unfortunately, I happen to have `<leader>` mapped to '\' (the default) and I happen to have `<leader><leader>` mapped to `<c-^>`, which I use all the time. 

The REPL mapping removes my own mapping, which is extremely annoying.

Ideally, this mapping would be customizable and/or should respect `g:slimv_keybindings`.

**Comment by kovisoft** [comment]
You can define a separate `<leader>` key used specifically by slimv by overriding `g:slimv_leader`. Please choose a `g:slimv_leader` that does not interfere with your existing keybindings.

**Comment by bvnierop** [comment]
That was staring me right in the face and I missed it. That solves my problem, thank you.
