### ISSUE TITLE
(read) on REPL buffer fails to read S-expressions

### ISSUE THREAD

**Issue by bvnierop** [kovisoft/slimv#43]
The following has been tried on both Windows and Linux with SBCL.

    >> (read)
    () <enter> works

    >> (read)
    (list 'a) <enter> does not work

    >> (read)
    (format t "hello, world!") <enter> does not work

**Comment by kovisoft** [comment]
Arglist display locked up `(read)` so I disabled it while in :read_string mode. See commit https://github.com/kovisoft/slimv/commit/871353d11d676faccc8750078d5f7319ba5e4bf3 .

**Comment by bvnierop** [comment]
Tested the fix and it works partially. When I use Ctrl+Space for autocompletion, it still hangs.

**Comment by kovisoft** [comment]
Thank you for the test. I had to disable swank-based autocompletion while in :read_string mode (i.e. in `(read)`). Autocompletion by symbols in hyperspec is still available. See commit https://github.com/kovisoft/slimv/commit/2dfa27a4be44da1970dea2282131508423c45e24 .

**Comment by bvnierop** [comment]
It's unfortunate that this is necessary, but the use case is rare enough that I don't think it's worth looking into much more. Thanks for the solution, and sorry for the late reply.
