### ISSUE TITLE
asdf:opertation-forced has been removed in asdf-3.2.0

### ISSUE THREAD

**Issue by nimiux** [kovisoft/slimv#50]
Last version of asdf removes several obsolete backward-compatible internals like operation-forced:

https://gitlab.common-lisp.net/asdf/asdf/commit/f5a25972884b8c44e6dabde722ff976f1aa221b8

Which is used in swank.asd:

https://github.com/kovisoft/slimv/blob/master/slime/swank.asd

Thanks for your code.

**Comment by kovisoft** [comment]
Thank you for the notification. I think the best way to handle this is that I'm going to update the swank server files (embedded in slimv) to the latest version from https://github.com/slime/slime. I hope it won't introduce some new incompatibilities.

**Comment by kovisoft** [comment]
I refreshed the embedded swank server to the latest version v2.18, see commit https://github.com/kovisoft/slimv/commit/f5f1405364cdd1113e2593342943f3bddd9ff1b0 .

**Comment by nimiux** [comment]
Nice. Works fine here. Closing issue
