### ISSUE TITLE
Python3: non-ASCII data gets botched

### ISSUE THREAD

**Issue by phmarek** [kovisoft/slimv#51]
When trying to transfer UTF8 data, de/encoding is broken somehow. For example, `§äöü` etc. don't get transmitted properly.

```
ValueError: invalid literal for int() with base 16: 00016(
```

This also happens when localized error messages (eg. `Verbindung zurückgewiesen`) are sent back to the editor.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/slimv/commit/ae0aa4fec10526e677435642d2bead054436fcc7 . Could you please check if the fix also works for you? Thank you.

**Comment by phmarek** [comment]
Seems to work just fine, thank you very much!
