### ISSUE TITLE
if indentation

### ISSUE THREAD

**Issue by oddg** [kovisoft/slimv#57]
I am struggling to get a proper indentation of the if special form.
The [proper indentation](http://dept-info.labri.fr/~idurand/enseignement/lst-info/PFS/Common/Strandh-Tutorial/indentation.html) should be
```lisp
(if (= (f x) 4)
    (top-level x)
    (g x))
```
but I get
```lisp
(if (= (f x) 4)
  (top-level x)
  (g x))
```
I looked into this answer given on [stackoverflow](http://stackoverflow.com/questions/6435595/new-slimv-0-8-4-install-paren-matching-works-indentation-doesnt) and I did run `:echo SlimvIndent(2)` that returns `2`. Is this the problem?

**Comment by oddg** [comment]
Actually I did not do enough [research](http://www.lispforum.com/viewtopic.php?f=17&t=4244) before opening this issue. Using `:set lispwords-=if` did the trick.

**Comment by kovisoft** [comment]
I have just read your bug report. Thank you for the feedback. Even if you found a workaround, I think this problem should be addressed in slimv, therefore I reopened this issue.

**Comment by kovisoft** [comment]
I fixed the indentation of `if` in commit https://github.com/kovisoft/slimv/commit/654145e455c4132149f1bcdf7be79bdc294f35cf , so you no longer need to tweak `lispwords`.

**Comment by oddg** [comment]
Great it works! Thank you.
