### ISSUE TITLE
syntax-rules indentation

### ISSUE THREAD

**Issue by alexdreptu** [kovisoft/slimv#59]
Next line after (syntax-rules () is indented at 16 chars, is this intended behavior? is there any option to change it?
For example:
```scheme
(define-syntax foo
  (syntax-rules ()
    (( ...
```
instead of
```scheme
(define-syntax foo
  (syntax-rules ()
                (( ...
```

**Comment by kovisoft** [comment]
This was a bug, thanks for reporting it. Fixed in commit https://github.com/kovisoft/slimv/commit/1e95b8d0b36db76a7049a124994cc2db57fa2366 .

**Comment by alexdreptu** [comment]
Thanks for fixing it so fast.
