### ISSUE TITLE
Shebang at start of file not ignored

### ISSUE THREAD

**Issue by alexpopov** [kovisoft/slimv#61]
I'm trying to learn Lisp by using it as a replacement for bash scripts. 

To this end, I have `#!/usr/bin/env sbcl --script` at the start of my Lisp scripts. 
However, if I run the buffer in slimv, I get an error triggered by that first line. 

Is there a way around this? 

Apologies if this issue should have been raised to the SBCL devs. 

[slimv_bt.txt](https://github.com/kovisoft/slimv/files/1027968/slimv_bt.txt)

**Comment by kovisoft** [comment]
Fixed it in commit https://github.com/kovisoft/slimv/commit/e7e4ceb85745dae06833edf27e162ad144824ef0 : skip shebang line when evaluating whole buffer.

**Comment by alexpopov** [comment]
Thank you so much for the quick fix!
