### ISSUE TITLE
Swank doesn't close... ever

### ISSUE THREAD

**Issue by benbotwin** [kovisoft/slimv#7]
Is there a way to get swank to close when vim does? or add a SlimvDissconect() function that would do the same?

**Comment by kovisoft** [comment]
I added a new command 'Quit REPL' to slimv that closes the swank server and terminates the lisp process running it. It is mapped to `<Leader>Q` by default. Please see commit https://github.com/kovisoft/slimv/commit/44a50afc5bfed414821fdb479e5a1f00df867e72
