### ISSUE TITLE
SlimvSelectForm should ignore comments

### ISSUE THREAD

**Issue by extrasharp** [kovisoft/slimv#71]
Hi!

I tracked down a bug that arises with the following code:
```
(defstruct foo
  bar0
  bar1)

(let ((var (make-foo :bar0 10
                     :bar1 10)))
   (foo-bar0 var))
``` 

When calling SlimvEvalDefun from within either top-level form, everything works okay.

If you comment out the `:bar1 10)))` line and readjust the parens, you have the following
```
(defstruct foo
  bar0
  bar1)

(let ((var (make-foo :bar0 10)))
                     ; :bar1 10)))
   (foo-bar0 var))
```

Now, if you call SlimvEvalDefun from within the `let`, the debugger is opened and shows "end of file on input stream ..."

Also the "s register only contains
```
(let ((var (make-foo :bar0 10)))
                     ; :bar1 10)
```

It would seem the problem is at line 1205 of ftplugin/slimv.vim, where `va(` is used to select the matching paren to the start of the top-level form. It would seem using searchpair would be better, so the code could skip comments and strings.

I have zero VimL experience otherwise I would try fixing it myself haha I might try within the next few days but I don't really know the idiomatic way to fix this.

**Comment by kovisoft** [comment]
Thanks for the feedback. Yes, I agree, the problem is with the `va(`. `%` is also failing in this case: when you place the cursor on the opening paren and press `%`, then it moves the cursor to the opening paren after `; :bar1 10`. This seems to be a bug in vim's built-in `%` handler, I'll try to find a workaround.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/slimv/commit/430fab13c243665c351d97632e2c7d76cfef67ca

**Comment by extrasharp** [comment]
Cool! I can confirm it works. Thanks
