### ISSUE TITLE
Stepper

### ISSUE THREAD

**Issue by kacoroski** [kovisoft/slimv#75]
Not really an issue - more like user confusion.  Just wondering what the trick is to get the sbcl stepper working with slimv.  Is there a way to do this?

Thanks for the slimv code.

cheers,

ski

**Comment by kovisoft** [comment]
TBH, I have never tried the sbcl steppen inside slimv. Now I tried it and it seems that `(step expr)` drops me in the swank debugger, where you can choose between various restarts (by moving the cursor and pressing Enter), each restart (or at least the first 4 of them) refers to the sbcl single stepping commands `stop/out/next/step`:

```
Restarts:
  0: [STEP-CONTINUE] Resume normal execution
  1: [STEP-OUT] Resume stepping after returning from this function
  2: [STEP-NEXT] Step over call
  3: [STEP-INTO] Step into call
  4: [RETRY] Retry SLIME REPL evaluation request.
  5: [*ABORT] Return to SLIME's top level.
  6: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1005048493}>)
```

**Comment by kacoroski** [comment]
This can be closed as code was committed to add in stepping commands.
