### ISSUE TITLE
Omni completion after tilde (~) character causes error

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/slimv#76]
Omni complete after a tilde (`~`) character always causes an error:

```
Error detected while processing function SlimvOmniComplete[7]..SlimvComplete:
line   46:
E33: No previous substitute regular expression
```

**How to reproduce**

1. Open a lisp file
2. Insert a tilde `~`
3. Omni complete (<kbd>Ctrl</kbd><kbd>x</kbd><kbd>Ctrl</kbd><kbd>o</kbd>)

The same error can be observed with tildes in comments, and with tildes in s-expressions. e.g. `(format t "~`

**Comment by kovisoft** [comment]
Thank you for the feedback. I confirm that this is a bug in Slimv. I'll inform you when I have a fix for the problem.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/slimv/commit/138539cbd7487be225613fd888714affcd1df257
