### ISSUE TITLE
Un-deletable character in REPL

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovisoft/slimv#77]
■ in REPL, Normal mode, press Enter
  ■ in the next prompted line, type "abc"
  ■ press Backspace 3 times
Notice that 'a' cannot be deleted.
<img width="104" alt="before-deletion" src="https://user-images.githubusercontent.com/7289591/65827194-55914180-e298-11e9-92a5-3b44992594f3.png">
<img width="82" alt="after-deletion" src="https://user-images.githubusercontent.com/7289591/65827193-55914180-e298-11e9-87f6-93db00383244.png">

Observation:
This behavior does not reproduce when moving to a custom package, for example:
```
(defpackage :tmc)
(in-package :tmc)
```

**Comment by kovisoft** [comment]
I confirm that this is a bug, thanks for reporting it.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/slimv/commit/c50c93fb4eb5f3a60be988aedabe35293afbb5f9

**Comment by mihaicristiantanase** [comment]
I've test it and it works. Thanks!
