### ISSUE TITLE
How can I customize the non-source-code buffers (REPL, INSPECT, etc.)?

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovisoft/slimv#78]
I'd like to set settings like no numbers row, no special characters, etc. for those buffers.
Is there a way to do that?
Thanks!

**Comment by kovisoft** [comment]
You can define vim autocommands that trigger when a buffer with a specific name is entered (also triggering when the buffer is created). For example if you don't want line numbers in the REPL and SLDB buffer then add these to your .vimrc file (use the name of the buffer for other buffer types as well):
```
:autocmd BufEnter REPL :setlocal nonumber
:autocmd BufEnter SLDB :setlocal nonumber
```

**Comment by mihaicristiantanase** [comment]
Works perfectly. Thanks!
