### ISSUE TITLE
Typo in Slimv Tutorial

### ISSUE THREAD

**Issue by susam** [kovisoft/slimv#91]
In [Slimv Tutorial - Part Two](https://kovisoft.bitbucket.io/tutorial2.html) there is a typo in the last sentence of the tutorial:

> Now package `split-sequece` is installed and ready for use in `morse-to-string`.

The same typo occurs in [Slimv Tutorial - Part Three](https://kovisoft.bitbucket.io/tutorial3.html) as well at the following two places:

> So far we have installed package `split-sequece`, so we can now write `morse-to-string`.

> Let's fix it by removing empty subsequences in `split-sequece:split-sequence`.

The package name `split-sequece` should be `split-sequence` instead.

**Comment by kovisoft** [comment]
Fixed it. Thank you for the feedback.
