### ISSUE TITLE
Please add support for ~/.slime-secret

### ISSUE THREAD

**Issue by gpiero** [kovisoft/slimv#97]
Just come back to `slimv` after some years as `vlime` user and at first it didn't work for me.
The spawned lisp (`sbcl 2.0.6`) showed:
```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "Swank 4005" RUNNING {10047F8903}>:
  Incoming connection doesn't know the password.
```
I could not find a reference to `~/.slime-secret` in the documentation, nor in slimv's source. At the moment, I have to remove `~/.slime-secret` in order to be able to use `slimv`.

**Comment by kovisoft** [comment]
Added support for ~/.slime-secret in commits https://github.com/kovisoft/slimv/commit/5345aa948bab484153ef153e10dde5e320c36383 and https://github.com/kovisoft/slimv/commit/b3da3d1b44541302d343089afe2b9608cc090281

**Comment by kovisoft** [comment]
Sorry, I didn't realize you filed a pull request. Anyway, I disabled logging of the password in commit https://github.com/kovisoft/slimv/commit/3c0ea5ed232ed30819c0ab2b1f6cfeb6ee849d22

**Comment by gpiero** [comment]
Thank you, it now works for the general case.
Anyway it still doesn't work for the corner case where `~/.slime-secret` is empty (`rm -f ~/.slime-secret; touch ~/.slime-secret`).
Yeah, I know it's a lame password, so I guess you could ignore it.

**Comment by kovisoft** [comment]
You are absolutely right, thanks for the feedback. I fixed the empty .slime-secret file case in commit https://github.com/kovisoft/slimv/commit/a0452f2d6ac7fbd4ca0b6c3777993052e8b103fc

**Comment by gpiero** [comment]
Thank you, closing as fixed.
